In [1]:
from utils import AOC
from session import SESSION

In [2]:
aoc = AOC(session=SESSION)

In [3]:
aoc.verify_session()

True

In [4]:
aoc.get_file(year=2022, day=1).analyse().head()

Local file found.
100% of data are digits. Analyse as numbers.
246 empty line(s) found. Analyse as multiline data.
===== HEAD (5/247) =====
[9057 8878 2753 7027 3880 7154 8022 6710 5721]
[4863 3690 3333 1831 5293 6258 1212 4255 2331 3785 1505 3355 3353 4416]
[5918 3076 2145 2712 6087 4310 1084 5807 1342 2770 5095 4696 5842 4555
 5388]
[20770]
[ 3968 15647  3933 15427 16179]


/home/bhasher/Documents/sync/dev/projects/personal/ProgrammingChallenges/utils_components/aoc2.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  self.data = np.array([self.parse(group.split('\n')) for group in self.raw.split('\n\n')])


In [6]:
max(map(sum, aoc.data))

69836

In [8]:
sd = sorted(map(sum, aoc.data))
sum(sd[-3:])

207968