In [1]:
from utils import Utils, AOC
from session import SESSION
from collections import defaultdict
from matplotlib import pyplot as plt
import numpy as np

In [2]:
aoc = AOC(session=SESSION)

In [3]:
aoc.verify_session()

True

In [38]:
aoc.get_today_file().analyse(monoline=False).head()

Local file found.
===== HEAD (2/2) =====
[[ 201  376]
 [ 706   92]
 [ 161  698]
 ...
 [ 519  142]
 [ 947  549]
 [1029   99]]
[655 447 327 223 163 111  81  55  40  27  13   6]


/home/bhasher/Documents/tech/projets/ProgrammingChallenges/utils_components/aoc2.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  self.data = np.array([self.parse(group.split('\n')) for group in self.raw.split('\n\n')])


In [39]:
folds = [el.removeprefix('fold along ').split('=') for el in aoc.raw.split('\n\n')[1].split('\n')]
folds = [(el[0], int(el[1])) for el in folds]

In [40]:
data = aoc.data[0]

In [48]:
coos = set([tuple(el) for el in data])

In [63]:
coos

array([[23,  4],
       [ 5,  1],
       [ 8,  0],
       [30,  0],
       [ 0,  5],
       [ 2,  2],
       [ 6,  2],
       [18,  1],
       [21,  0],
       [ 7,  1],
       [36,  0],
       [17,  5],
       [ 5,  3],
       [30,  2],
       [32,  5],
       [35,  1],
       [13,  1],
       [18,  3],
       [ 7,  3],
       [ 5,  5],
       [30,  4],
       [ 0,  0],
       [11,  0],
       [35,  3],
       [15,  0],
       [13,  3],
       [26,  0],
       [22,  5],
       [ 3,  1],
       [28,  0],
       [13,  5],
       [26,  2],
       [25,  4],
       [15,  2],
       [ 1,  3],
       [38,  4],
       [20,  1],
       [37,  5],
       [ 5,  0],
       [33,  1],
       [ 1,  5],
       [15,  4],
       [18,  0],
       [20,  3],
       [22,  0],
       [ 3,  5],
       [ 5,  2],
       [33,  3],
       [10,  1],
       [16,  5],
       [18,  2],
       [31,  5],
       [23,  1],
       [37,  0],
       [ 5,  4],
       [10,  3],
       [35,  2],
       [13,  2],
       [25,  1

In [49]:
len(coos)

866

In [52]:
for axe, n in folds:
    new = set()
    for co in coos:
        co = list(co)
        if axe == 'y' and co[1] > n:
            co[1] = 2*n-co[1]
        if axe == 'x' and co[0] > n:
            co[0] = 2*n-co[0]
        new.add(tuple(co))
    coos = new

In [57]:
coos = np.array(list(coos))

In [58]:
map = np.zeros(coos.max(axis=0)+1)

In [59]:
for x,y in coos:
    map[x,y] = 1

In [61]:
def display(m):
    for line in m.T:
        print(''.join(['.' if el == 0 else '#' for el in line]))

In [62]:
display(map)

####.#..#..##..#..#..##..####.#..#..##.
...#.#.#..#..#.#..#.#..#.#....#..#.#..#
..#..##...#..#.#..#.#....###..#..#.#...
.#...#.#..####.#..#.#....#....#..#.#...
#....#.#..#..#.#..#.#..#.#....#..#.#..#
####.#..#.#..#..##...##..#.....##...##.


In [ ]:
# ZKAUCFUC