In [1]:
from utils import Utils, AOC
from session import SESSION
import numpy as np

In [2]:
aoc = AOC(session=SESSION)

In [3]:
aoc.verify_session()

True

In [4]:
aoc.get_file(year=2021, day=4).analyse().head()

Local file found.
100% of data are digits. Analyse as numbers.
100 empty line(s) found. Analyse as multiline data.
===== HEAD (5/101) =====
[67  3 19  4 64 39 85 14 84 93 79 26 61 24 65 63 15 69 48  8 82 75 36 96
 16 49 28 40 97 38 76 91 83  7 62 94 21 95  6 10 43 17 31 34 81 23 52 60
 54 29 70 12 35  0 57 45 20 71 78 44 90  2 33 68 53 92 50 73 88 47 58  5
  9 87 22 13 18 30 59 56 99 11 77 55 72 32 37 89 42 27 66 41 86 51 74  1
 46 25 98 80]
[[24 75 59 41 17]
 [58 74 64 92 39]
 [68  8 78 85 72]
 [18  3 22  4 34]
 [11 76  6 28 50]]
[[21 31 36 13 87]
 [80 91 63 62 77]
 [46 93 40 16 25]
 [47 66 30 54 74]
 [56 59 86 72 37]]
[[92 43 68 60 81]
 [ 3 78 75 73 12]
 [90 50 31 67 76]
 [28 63 52 95 61]
 [ 6 38 79 19 17]]
[[81 20 61 60 86]
 [43 27 50 21 85]
 [77 84 68 76 24]
 [33 13 89  1 48]
 [ 6 57 30 11  5]]


/home/bhasher/Documents/tech/projets/ProgrammingChallenges/utils_components/aoc2.py:101: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  self.data = np.array([self.parse(group.split('\n')) for group in self.raw.split('\n\n')])


In [9]:
numbers, *tables = aoc.data
marks = np.array(tables)
marks.fill(1)

In [10]:
def mark(number):
    for i in range(len(tables)):
        for loc in zip(*np.where(tables[i]==number)):
            print(loc)
            marks[i][loc] = 0
            tables[i][loc] = 0

In [11]:
def check():
    for i in range(len(tables)):
        if min(min(marks[i].sum(axis=0)), min(marks[i].sum(axis=1))) == 0:
            return i

In [13]:
for n in numbers:
    mark(n)
    c = check()
    if c is not None:
        #print(n, c)
        break

In [16]:
tables[c].sum() * n

49513

In [17]:
def check2():
    v = set()
    for i in range(len(tables)):
        if min(min(marks[i].sum(axis=0)), min(marks[i].sum(axis=1))) == 0:
            v.add(i)
    if len(v) == len(tables):
        return set(range(len(tables))).difference(v)

In [19]:
for n in numbers:
    mark(n)
    c = check2()
    if c is not None:
        #print(n, c)
        break

In [20]:
# < 15895
# = 8224

In [21]:
tables[83].sum() * n

17219

In [22]:
tables[83]

array([[ 0, 27,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0, 25,  0,  0],
       [41,  0,  0,  0, 98],
       [ 0,  0,  0, 66,  0]])