In [49]:
from __future__ import annotations
import math
from utils import Utils, AOC
from session import SESSION
from collections import defaultdict
from functools import reduce
from itertools import permutations
import numpy as np
import re

[(0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)]

In [2]:
aoc = AOC(session=SESSION)

In [3]:
aoc.verify_session()

True

In [10]:
aoc.raw = """--- scanner 0 ---
404,-588,-901
528,-643,409
-838,591,734
390,-675,-793
-537,-823,-458
-485,-357,347
-345,-311,381
-661,-816,-575
-876,649,763
-618,-824,-621
553,345,-567
474,580,667
-447,-329,318
-584,868,-557
544,-627,-890
564,392,-477
455,729,728
-892,524,684
-689,845,-530
423,-701,434
7,-33,-71
630,319,-379
443,580,662
-789,900,-551
459,-707,401

--- scanner 1 ---
686,422,578
605,423,415
515,917,-361
-336,658,858
95,138,22
-476,619,847
-340,-569,-846
567,-361,727
-460,603,-452
669,-402,600
729,430,532
-500,-761,534
-322,571,750
-466,-666,-811
-429,-592,574
-355,545,-477
703,-491,-529
-328,-685,520
413,935,-424
-391,539,-444
586,-435,557
-364,-763,-893
807,-499,-711
755,-354,-619
553,889,-390

--- scanner 2 ---
649,640,665
682,-795,504
-784,533,-524
-644,584,-595
-588,-843,648
-30,6,44
-674,560,763
500,723,-460
609,671,-379
-555,-800,653
-675,-892,-343
697,-426,-610
578,704,681
493,664,-388
-671,-858,530
-667,343,800
571,-461,-707
-138,-166,112
-889,563,-600
646,-828,498
640,759,510
-630,509,768
-681,-892,-333
673,-379,-804
-742,-814,-386
577,-820,562

--- scanner 3 ---
-589,542,597
605,-692,669
-500,565,-823
-660,373,557
-458,-679,-417
-488,449,543
-626,468,-788
338,-750,-386
528,-832,-391
562,-778,733
-938,-730,414
543,643,-506
-524,371,-870
407,773,750
-104,29,83
378,-903,-323
-778,-728,485
426,699,580
-438,-605,-362
-469,-447,-387
509,732,623
647,635,-688
-868,-804,481
614,-800,639
595,780,-596

--- scanner 4 ---
727,592,562
-293,-554,779
441,611,-461
-714,465,-776
-743,427,-804
-660,-479,-426
832,-632,460
927,-485,-438
408,393,-506
466,436,-512
110,16,151
-258,-428,682
-393,719,612
-211,-452,876
808,-476,-593
-575,615,604
-485,667,467
-680,325,-822
-627,-443,-432
872,-547,-609
833,512,582
807,604,487
839,-516,451
891,-625,532
-652,-548,-490
30,-46,-14"""

In [11]:
#aoc.get_today_file()
aoc.analyse(numeric=False).head()

===== HEAD (5/5) =====
['--- scanner 0 ---', '404,-588,-901', '528,-643,409', '-838,591,734', '390,-675,-793', '-537,-823,-458', '-485,-357,347', '-345,-311,381', '-661,-816,-575', '-876,649,763', '-618,-824,-621', '553,345,-567', '474,580,667', '-447,-329,318', '-584,868,-557', '544,-627,-890', '564,392,-477', '455,729,728', '-892,524,684', '-689,845,-530', '423,-701,434', '7,-33,-71', '630,319,-379', '443,580,662', '-789,900,-551', '459,-707,401']
['--- scanner 1 ---', '686,422,578', '605,423,415', '515,917,-361', '-336,658,858', '95,138,22', '-476,619,847', '-340,-569,-846', '567,-361,727', '-460,603,-452', '669,-402,600', '729,430,532', '-500,-761,534', '-322,571,750', '-466,-666,-811', '-429,-592,574', '-355,545,-477', '703,-491,-529', '-328,-685,520', '413,935,-424', '-391,539,-444', '586,-435,557', '-364,-763,-893', '807,-499,-711', '755,-354,-619', '553,889,-390']
['--- scanner 2 ---', '649,640,665', '682,-795,504', '-784,533,-524', '-644,584,-595', '-588,-843,648', '-30,6,44',

/home/bhasher/Documents/development/projects/personal/ProgrammingChallenges/utils_components/aoc2.py:104: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  self.data = np.array([group.split('\n') for group in self.raw.split('\n\n')])


In [12]:
aoc.data

array([list(['--- scanner 0 ---', '404,-588,-901', '528,-643,409', '-838,591,734', '390,-675,-793', '-537,-823,-458', '-485,-357,347', '-345,-311,381', '-661,-816,-575', '-876,649,763', '-618,-824,-621', '553,345,-567', '474,580,667', '-447,-329,318', '-584,868,-557', '544,-627,-890', '564,392,-477', '455,729,728', '-892,524,684', '-689,845,-530', '423,-701,434', '7,-33,-71', '630,319,-379', '443,580,662', '-789,900,-551', '459,-707,401']),
       list(['--- scanner 1 ---', '686,422,578', '605,423,415', '515,917,-361', '-336,658,858', '95,138,22', '-476,619,847', '-340,-569,-846', '567,-361,727', '-460,603,-452', '669,-402,600', '729,430,532', '-500,-761,534', '-322,571,750', '-466,-666,-811', '-429,-592,574', '-355,545,-477', '703,-491,-529', '-328,-685,520', '413,935,-424', '-391,539,-444', '586,-435,557', '-364,-763,-893', '807,-499,-711', '755,-354,-619', '553,889,-390']),
       list(['--- scanner 2 ---', '649,640,665', '682,-795,504', '-784,533,-524', '-644,584,-595', '-588,-843,

In [256]:
sc0 = np.array([list(map(int,el.split(','))) for el in aoc.data[0][1:]])
sc1 = np.array([list(map(int,el.split(','))) for el in aoc.data[1][1:]])

In [257]:
sc0r = np.sort(sc0, axis=0)[0]

In [258]:
sc0r

array([-892, -824, -901])

In [251]:
rotations = []
for i, j, k in permutations(range(3), 3):
    sc = sc1[:, [i, j, k]]
    for l in range(2**3):
        ri = 1 if l%2 else -1
        rj = 1 if l//2%2 else -1
        rk = 1 if l//4%2 else -1
        scr = sc * (ri, rj, rk)
        scr.sort(axis=0)
        rotations.append((sc, scr - scr[0]))

In [252]:
len(rotations)

48

In [253]:
diffs = {}
for i, (real, relative) in enumerate(rotations):
    diffs[i] = [real_line for real_line, relative_line in zip(real, relative) if relative_line in sc0]

In [254]:
sc0

array([[ 404, -588, -901],
       [ 528, -643,  409],
       [-838,  591,  734],
       [ 390, -675, -793],
       [-537, -823, -458],
       [-485, -357,  347],
       [-345, -311,  381],
       [-661, -816, -575],
       [-876,  649,  763],
       [-618, -824, -621],
       [ 553,  345, -567],
       [ 474,  580,  667],
       [-447, -329,  318],
       [-584,  868, -557],
       [ 544, -627, -890],
       [ 564,  392, -477],
       [ 455,  729,  728],
       [-892,  524,  684],
       [-689,  845, -530],
       [ 423, -701,  434],
       [   7,  -33,  -71],
       [ 630,  319, -379],
       [ 443,  580,  662],
       [-789,  900, -551],
       [ 459, -707,  401]])

In [255]:
diffs

{0: [array([686, 422, 578]),
  array([605, 423, 415]),
  array([ 515,  917, -361]),
  array([-476,  619,  847]),
  array([ 669, -402,  600]),
  array([-500, -761,  534]),
  array([-466, -666, -811]),
  array([-429, -592,  574]),
  array([-355,  545, -477]),
  array([ 703, -491, -529]),
  array([-328, -685,  520]),
  array([ 413,  935, -424])],
 1: [array([686, 422, 578]),
  array([605, 423, 415]),
  array([ 515,  917, -361]),
  array([-476,  619,  847]),
  array([ 669, -402,  600]),
  array([-500, -761,  534]),
  array([-466, -666, -811]),
  array([-429, -592,  574]),
  array([-355,  545, -477]),
  array([ 703, -491, -529]),
  array([-328, -685,  520]),
  array([ 413,  935, -424])],
 2: [array([686, 422, 578]),
  array([605, 423, 415]),
  array([ 515,  917, -361]),
  array([-476,  619,  847]),
  array([ 669, -402,  600]),
  array([-500, -761,  534]),
  array([-466, -666, -811]),
  array([-429, -592,  574]),
  array([-355,  545, -477]),
  array([ 703, -491, -529]),
  array([-328, -685, 

# Not finished yet